### ISSUE TITLE
Loading images twice when element.top is 0

### ISSUE THREAD

**Issue by martin104** [Angrycreative/bj-lazy-load#48] opened 2019-05-17 19:11 UTC
In a custom WP installation where LayGridder plugin is used to display grids with images, somehow on any event triggered (load,scroll,resize) all the images were loaded twice - one time with element.top equal to 0 (thus triggering all of them to be loaded at once) and second time with actual distance from the top (not triggering load on any not in the viewport).

My simple solution was to change the code to (adding a check if elemRect.top>0): 
`if ( winH - elemRect.top + BJLL.threshold > 0 && elemRect.top>0 ) {
        BJLL.show( el );
	updated = true;
}`

May not be an issue for everybody, but good to know.

**Comment by jan-san** [comment] 2019-07-01 09:40
The `element.top` = 0 elements might have been caused by `display:none`. The loading of such hidden images was fixed in b360afdc7517e969f72e180a423bdfe4ad2bb971
Please reopen this issue if the problem still persists.

**Closed by jan-san** 2019-07-01 09:40 UTC
